INSERT INTO flight
(AIRLINE_CODE, FLIGHT_NUM, FLIGHT_DATE, ORIGIN, DEST, DEP_TIME, ARR_TIME, AIRPLANE_MODEL)
VALUES ('IR', '123', '05Feb', 'THR', 'MHD', '1730', '1830', 'BW');


INSERT INTO SEAT_CLASS
(CLASS_NAME, ORIGIN, DEST, AIRLINE_CODE, ADULT_PRICE, CHILD_PRICE, INFANT_PRICE)
VALUES ('Y', 'THR', 'MHD', 'IR', 3000, 2000, 1000);

INSERT INTO SEAT_CLASS
(CLASS_NAME, ORIGIN, DEST, AIRLINE_CODE, ADULT_PRICE, CHILD_PRICE, INFANT_PRICE)
VALUES ('C', 'THR', 'MHD', 'IR', 3500, 2500, 1500);


INSERT INTO FLIGHT_SEAT_CLASS
(FID, SID)
VALUES (0, 0);

INSERT INTO FLIGHT_SEAT_CLASS
(FID, SID)
VALUES (0, 1);