INSERT INTO flight
(AIRLINE_CODE, FLIGHT_NUM, FLIGHT_DATE, ORIGIN, DEST, DEP_TIME, ARR_TIME, AIRPLANE_MODEL)
VALUES ('IR', '123', '05Feb', 'THR', 'MHD', '1730', '1830', 'BW');


INSERT INTO SEAT_CLASS
(CLASS_NAME, ORIGIN, DEST, AIRLINE_CODE, ADULT_PRICE, CHILD_PRICE, INFANT_PRICE)
VALUES ('Y', 'THR', 'MHD', 'IR', 3000, 2000, 1000);

INSERT INTO SEAT_CLASS
(CLASS_NAME, ORIGIN, DEST, AIRLINE_CODE, ADULT_PRICE, CHILD_PRICE, INFANT_PRICE)
VALUES ('C', 'THR', 'MHD', 'IR', 3500, 2500, 1500);


INSERT INTO FLIGHT_SEAT_CLASS
(FID, SID)
VALUES (0, 0);

INSERT INTO FLIGHT_SEAT_CLASS
(FID, SID)
VALUES (0, 1);

INSERT INTO PERSON
(PID, FIRST_NAME, SUR_NAME, GENDER, age_type, nationalId)
VALUES ('1234567890', 'Ali', 'Akhavani', 'male', 'infant', '124567890')

INSERT INTO reserve
(token, fid, sid, adult_count, child_count, infant_count)
('123', 12, 34, 1, 2, 1)

INSERT INTO ticket (tid, rid, pid) VALUES ('asdf', 'zxc', 'vbn');