SELECT * FROM flight WHERE FLIGHT_DATE = '05Feb' AND ORIGIN = 'THR' AND DEST = 'MHD';

SELECT * FROM flight WHERE FLIGHT_NUM = '452' AND origin = 'THR' AND dest = 'MHD' AND FLIGHT_DATE = '05Feb'

SELECT * FROM flight_seat_class WHERE FID = 0;


SELECT * FROM seat_class WHERE SID = 1;